CREATE TABLE SUPERVISOR
(
	Department_ID	INT(4)		NOT NULL,
	Supervisor_ID	INT(10)		NOT NULL,
	
	FOREIGN KEY(Department_ID)
		REFERENCES DEPARTMENT(Dept_ID),
	FOREIGN KEY(Supervisor_ID)
		REFERENCES EMPLOYEE(ID)
);